import Link from "next/link";
import { ShieldCheck } from "lucide-react";

const content = {
  safety: { title: "Search carefully. Verify independently.", lead: "A verification label can reduce uncertainty, but it cannot replace your own review of the property, provider, lease, and payment method.", sections: [["Before you send money", "Never send money before verifying the property, the person offering it, the lease, and the payment method. Avoid wire transfers, gift cards, cryptocurrency, and pressure to pay before a tour."], ["Check the listing facts", "Compare the public address, provider identity, source, price history, fee breakdown, and availability. Ask for clarification when details conflict."], ["Report suspicious behavior", "Use the report control on a listing. Reports create a moderation case; automated signals do not silently ban a provider."]] },
  help: { title: "How can we help?", lead: "Answers for renters and housing providers using the Houston marketplace demo.", sections: [["For renters", "Search by location and factual housing features, compare monthly and move-in totals, save rentals, and contact providers privately."], ["For providers", "Submit complete pricing and provenance, attest to advertising authority, and respond to moderation requests and leads."], ["Need support?", "In production, support requests are routed without exposing private listing or lead data to analytics."]] },
  pricing: { title: "Simple provider pricing", lead: "The MVP does not sell placement inside organic rankings.", sections: [["Renter access", "Search, cost comparison, safety information, and reporting are free."], ["Provider plans", "Flat-fee provider subscriptions are an optional future integration. Billing is disabled until Stripe and jurisdiction rules are configured."], ["Sponsored placement", "When enabled later, sponsored listings occupy separate configured slots, carry a visible Sponsored label, and never silently replace organic results."]] },
  privacy: { title: "Privacy by design", lead: "We collect only what the rental-discovery and lead-routing workflows need.", sections: [["Data we avoid", "We do not store Social Security numbers, credit reports, criminal or eviction reports, bank credentials, payment cards, biometric templates, or tenant-screening documents."], ["Your choices", "Production accounts can export or delete profile data and control alert, email, and analytics preferences."], ["Analytics", "We exclude private message bodies, identity documents, access tokens, and unnecessary personally identifiable information from analytics."]] },
  terms: { title: "Marketplace terms summary", lead: "This product is a listing discovery, aggregation, and lead-routing platform—not a real-estate broker, leasing negotiator, screening company, payment custodian, or escrow service.", sections: [["Listing responsibility", "Providers are responsible for their authority, media rights, listing facts, pricing, fees, availability, and legal compliance."], ["Renter responsibility", "Renters must independently verify listings, providers, leases, and payment methods."], ["Demo inventory", "Local fixtures are synthetic, clearly labeled, and must never be published as real inventory."]] },
  accessibility: { title: "Accessibility commitment", lead: "The application targets WCAG 2.2 AA and provides a list alternative for every map result.", sections: [["Interaction", "Core search, filter, save, compare, contact, provider, and moderation flows support keyboard navigation and visible focus."], ["Content", "Headings, labels, status text, alt text, errors, and live result counts provide nonvisual context. Color is never the only verification signal."], ["Testing", "Automated axe checks complement—not replace—manual keyboard, zoom, high contrast, VoiceOver, NVDA, and TalkBack testing."]] },
} as const;

export function ContentPage({ kind }: { kind: keyof typeof content }) { const page = content[kind]; return <main className="container content-page"><p className="kicker">Marketplace guidance</p><h1>{page.title}</h1><p className="lead">{page.lead}</p>{kind === "safety" && <div className="legal-note"><ShieldCheck/> <strong>Never send money before verifying the property, the person offering it, the lease, and the payment method.</strong></div>}{page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}<div className="info-card"><strong>Need to take action?</strong><p><Link className="text-link" href={kind === "safety" ? "/search" : "/help"}>{kind === "safety" ? "Return to Houston rental search" : "Visit the help center"}</Link></p></div></main>; }
