import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import { ListingCard } from "@/components/listings/ListingCard";
import { houstonNeighborhoods, publicHoustonListings } from "@/data/houston-listings";

export function LocationLanding({ neighborhood }: { neighborhood?: string }) {
  const name = neighborhood ?? "Houston";
  const listings = neighborhood ? publicHoustonListings.filter((item) => item.neighborhood.toLowerCase().replace(/\s+/g, "-") === neighborhood.toLowerCase()).slice(0, 6) : publicHoustonListings.slice(0, 6);
  return <main><section className="hero" style={{ minHeight: 390 }}><div className="container hero-content" style={{ minHeight: 390, gridTemplateColumns: "1fr" }}><div className="hero-copy"><p className="eyebrow"><MapPin size={16}/>Houston launch market</p><h1>Rentals in {name === "Houston" ? "Houston, Texas" : name}</h1><p className="hero-lede">Explore synthetic inventory with visible source records, freshness, and estimated total monthly costs.</p><Link className="button button-coral" href={neighborhood ? `/search?neighborhood=${encodeURIComponent(name)}` : "/search"}>Search available rentals <ArrowRight size={17}/></Link></div></div></section><section className="container listing-shelf"><div className="section-heading"><div><p className="kicker">Current demo inventory</p><h2>{listings.length} featured rentals</h2></div></div>{listings.length ? <div className="listing-grid">{listings.map((listing) => <ListingCard listing={listing} key={listing.id}/>)}</div> : <div className="empty-results"><h2>No indexable inventory here yet</h2><p>We do not generate thin neighborhood landing pages without enough active inventory.</p><Link className="button button-ink" href="/rentals/houston-tx">Explore Houston</Link></div>}</section>{!neighborhood && <section className="neighborhood-section"><div className="container"><div className="section-heading"><h2>Explore Houston-area locations</h2></div><div className="neighborhood-links">{houstonNeighborhoods.map((item) => <Link key={item} href={`/rentals/houston-tx/${item.toLowerCase().replace(/\s+/g, "-")}`}>{item}<ArrowRight size={15}/></Link>)}</div></div></section>}</main>;
}
