"use client";

import { useState } from "react";
import Link from "next/link";
import { BadgeCheck, Building2, ChartNoAxesCombined, Clock3, MessageSquareText } from "lucide-react";

export function ProviderDashboard({ section = "overview" }: { section?: string }) {
  const [leadState, setLeadState] = useState("new");
  const title = section === "overview" ? "Provider command center" : section.replaceAll("-", " ").replace(/\b\w/g, (value) => value.toUpperCase());
  return <main className="dashboard-page"><div className="container"><header className="dashboard-hero"><div><p className="kicker">Demo provider portal</p><h1>{title}</h1><p>Sample Small Landlord · Property authority attested · Manual review pending</p></div><Link href="/provider/listings/new" className="button button-coral">Create listing</Link></header><div className="stat-grid"><div className="stat-card"><Building2/><span>Active listings</span><strong>4</strong></div><div className="stat-card"><MessageSquareText/><span>New leads</span><strong>7</strong></div><div className="stat-card"><Clock3/><span>Median response</span><strong>2.4h</strong></div><div className="stat-card"><ChartNoAxesCombined/><span>30-day views</span><strong>1,284</strong></div></div><div className="dashboard-grid"><section className="dashboard-card"><h2>Inventory requiring attention</h2><div className="table-row"><div><strong>Live Oak Apartment 01</strong><br/><small>Fees 100% complete</small></div><span>Updated today</span><span className="status">Published</span><Link href="/provider/listings/1/edit">Edit</Link></div><div className="table-row"><div><strong>Bayou House 02</strong><br/><small>Renew by Jul 25</small></div><span>7 days</span><span className="status warning">Expiring</span><button className="compare-button" type="button">Renew</button></div><div className="table-row"><div><strong>Juniper Townhouse 05</strong><br/><small>Moderator requested fee clarification</small></div><span>2 issues</span><span className="status warning">Needs review</span><Link href="/provider/listings/5/edit">Resolve</Link></div></section><aside className="dashboard-card"><h2>Provider setup</h2><div className="action-list"><Link href="/provider/verification"><BadgeCheck size={16}/> Verification center</Link><Link href="/provider/listings">Manage listings</Link><Link href="/provider/leads">Leads</Link><Link href="/provider/analytics">Performance</Link><Link href="/provider/settings">Contact & routing settings</Link></div></aside></div><section className="dashboard-card" style={{ marginTop: 18 }}><h2>Latest lead</h2><div className="table-row"><div><strong>Jordan R.</strong><br/><small>Asked about Live Oak Apartment 01. Private email is available only in the authorized lead view.</small></div><span>12 minutes ago</span><select className="field" aria-label="Lead status" value={leadState} onChange={(event) => setLeadState(event.target.value)}><option value="new">New</option><option value="contacted">Contacted</option><option value="tour_requested">Tour requested</option><option value="closed">Closed</option><option value="spam">Spam</option></select><span className="status">{leadState.replaceAll("_", " ")}</span></div></section></div></main>;
}
