import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck, Check, Clock3, ExternalLink, MapPin, ShieldAlert } from "lucide-react";
import { getListingBySlug, publicHoustonListings } from "@/data/houston-listings";
import { calculateTotalCost, formatMoney } from "@/lib/total-cost/calculate";
import { freshnessLabel, verificationLabel } from "@/lib/trust-safety/listing-trust";
import { ListingActions } from "@/components/listings/ListingActions";
import { ContactCard } from "@/components/listings/ContactCard";
import { ListingCard } from "@/components/listings/ListingCard";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const listing = getListingBySlug((await params).slug);
  if (!listing) return { title: "Listing not found" };
  return { title: `${listing.title} in ${listing.neighborhood}`, description: `${listing.bedrooms} bedroom ${listing.propertyType} with an advertised rent of ${formatMoney(listing.advertisedRentCents)}. Synthetic demo listing.`, alternates: { canonical: `/listing/${listing.slug}` } };
}

export default async function ListingPage({ params }: { params: Promise<{ slug: string }> }) {
  const listing = getListingBySlug((await params).slug);
  if (!listing) notFound();
  const cost = calculateTotalCost({ baseRentCents: listing.advertisedRentCents, leaseMonths: listing.leaseMonths, charges: listing.charges, concessions: listing.concessions });
  const verified = verificationLabel(listing);
  const similar = publicHoustonListings.filter((item) => item.id !== listing.id && (item.neighborhood === listing.neighborhood || item.propertyType === listing.propertyType)).slice(0, 3);
  const jsonLd = { "@context": "https://schema.org", "@type": listing.propertyType === "house" ? "SingleFamilyResidence" : "Apartment", name: listing.title, address: { "@type": "PostalAddress", addressLocality: listing.city, addressRegion: "TX", postalCode: listing.zip }, offers: { "@type": "Offer", priceCurrency: "USD", price: listing.advertisedRentCents / 100, availability: "https://schema.org/InStock" } };
  return <main className="listing-detail"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/search">Houston rentals</Link><span>/</span><Link href={`/search?neighborhood=${encodeURIComponent(listing.neighborhood)}`}>{listing.neighborhood}</Link><span>/</span><span>{listing.title}</span></nav>
    <div className="listing-gallery"><div><Image src={listing.image} fill preload loading="eager" sizes="(max-width: 720px) 100vw, 70vw" alt={`Synthetic illustration for ${listing.title}`} /></div><div><Image src={`/images/rental-${listing.image.includes("1") ? 2 : 1}.svg`} fill sizes="30vw" alt="Additional synthetic exterior illustration" /></div><div><Image src="/images/rental-4.svg" fill sizes="30vw" alt="Synthetic furnished interior illustration" /></div></div>
    <div className="detail-layout"><article><header className="detail-header"><div><p className="kicker">{listing.synthetic ? "Synthetic development listing" : listing.propertyType}</p><h1>{listing.title}</h1><p className="detail-subtitle"><MapPin size={15} /> {listing.addressDisplay} · {listing.neighborhood}, {listing.state} {listing.zip}</p></div><ListingActions listingId={listing.id} title={listing.title} /></header>
      <div className="detail-trust-row">{verified ? <span className="detail-pill"><BadgeCheck size={16} />{verified}</span> : <span className="detail-pill">No active verification record</span>}<span className="detail-pill"><Clock3 size={16} />{freshnessLabel(listing.updatedAt, new Date("2026-07-15T12:00:00Z"))}</span><span className="detail-pill">Source: {listing.source.name}</span></div>
      <div className="cost-overview"><div><span>Contract rent</span><strong>{formatMoney(cost.advertisedRentCents)}</strong><small>per month</small></div><div><span>Effective rent</span><strong>{formatMoney(cost.effectiveRentCents)}</strong><small>{listing.leaseMonths}-month term</small></div><div><span>Estimated monthly total</span><strong>{formatMoney(cost.estimatedTotalMonthlyCents)}</strong><small>required + estimated</small></div><div><span>Estimated due at move-in</span><strong>{formatMoney(cost.estimatedDueAtMoveInCents)}</strong><small>before optional charges</small></div></div>
      <section className="detail-section"><h2>About this rental</h2><p>{listing.description}</p><div className="fact-grid"><div><span>Home type</span><strong>{listing.propertyType}</strong></div><div><span>Bedrooms / bathrooms</span><strong>{listing.bedrooms === 0 ? "Studio" : listing.bedrooms} / {listing.bathrooms}</strong></div><div><span>Interior</span><strong>{listing.squareFeet?.toLocaleString()} sq ft</strong></div><div><span>Available</span><strong>{new Date(`${listing.availableOn}T12:00:00`).toLocaleDateString()}</strong></div><div><span>Lease</span><strong>{listing.leaseMonths} months</strong></div><div><span>Furnished</span><strong>{listing.furnished ? "Yes" : "No"}</strong></div></div></section>
      <section className="detail-section"><h2>Monthly and move-in costs</h2><p>Provider-reported charges are shown separately from platform estimates. Ranged charges use a midpoint for the estimate.</p><div className="fee-table"><div className="fee-row"><strong>Contract rent</strong><span>Required · monthly</span><strong>{formatMoney(listing.advertisedRentCents)}</strong></div>{listing.charges.map((fee) => <div className="fee-row" key={fee.id}><strong>{fee.name}<span>{fee.source === "platform_estimated" ? "Platform estimate" : "Provider reported"}</span></strong><span>{fee.required ? "Required" : "Optional"} · {fee.refundable ? "Refundable" : "Nonrefundable"}</span><strong>{fee.amount.type === "range" ? `${formatMoney(fee.amount.minimumCents)}–${formatMoney(fee.amount.maximumCents)}` : fee.amount.type === "percentage" ? `${fee.amount.basisPoints / 100}%` : formatMoney(fee.amount.cents)}{fee.cadence === "monthly" ? "/mo" : ""}</strong></div>)}</div>{listing.concessions.length > 0 && <div className="info-card"><strong>Concession</strong><p>{listing.concessions[0].value} free {listing.concessions[0].kind.replace("free_", "")} on the eligible {listing.leaseMonths}-month term. Contract rent remains due according to the lease schedule.</p></div>}</section>
      <section className="detail-section"><h2>Amenities and policies</h2><ul className="amenity-grid">{[...listing.amenities, ...listing.accessibility].map((item) => <li key={item}><Check size={16} />{item}</li>)}</ul><div className="fact-grid"><div><span>Pets</span><strong>{listing.petPolicy.replaceAll("_", " ")}</strong></div><div><span>Parking</span><strong>{listing.parking}</strong></div><div><span>Utilities included</span><strong>{listing.utilitiesIncluded.join(", ") || "None reported"}</strong></div></div>{listing.providerReportedVoucherAcceptance && <p className="info-card"><strong>Voucher acceptance:</strong> provider reported. Confirm current program and unit eligibility directly.</p>}</section>
      <section className="detail-section"><h2>Location</h2><p>{listing.addressDisplay.includes("Near") ? "The provider chose an approximate public location. Exact address is shared through an approved contact flow." : "The provider approved this address for public display."}</p><div className="mock-map mock-map-small"><span className="map-pin active" style={{ left: "50%", top: "50%" }}>{formatMoney(listing.advertisedRentCents)}</span></div></section>
      <section className="detail-section"><h2>Provider and listing provenance</h2><div className="source-card"><h3>{listing.provider.name}</h3><p>{listing.provider.responseTime} · {listing.provider.listingCount} active synthetic listing(s)</p><p><strong>Listing source:</strong> {listing.source.name}<br/><strong>Last synchronized:</strong> {new Date(listing.source.synchronizedAt).toLocaleString()}<br/><strong>Expires:</strong> {new Date(listing.expiresAt).toLocaleDateString()}</p>{verified && <p><BadgeCheck size={15} /> Active verification method: {listing.verificationRecords[0].method}; last verified {new Date(listing.verificationRecords[0].verifiedAt).toLocaleDateString()}.</p>}</div></section>
      <section className="detail-section"><h2>Price history</h2><div className="fact-grid"><div><span>Jul 2026</span><strong>{formatMoney(listing.advertisedRentCents)}</strong></div><div><span>Jun 2026</span><strong>{formatMoney(listing.advertisedRentCents + 5_000)}</strong></div><div><span>Change</span><strong>↓ {formatMoney(5_000)}</strong></div></div></section>
    </article><ContactCard listing={listing} /></div>
    <section className="listing-shelf"><div className="section-heading"><div><p className="kicker">Keep comparing</p><h2>Similar synthetic rentals</h2></div></div><div className="listing-grid">{similar.map((item) => <ListingCard key={item.id} listing={item} />)}</div></section>
    <section className="safety-callout"><ShieldAlert /><div><strong>Never send money before verifying the property, the person offering it, the lease, and the payment method.</strong><p>This marketplace does not collect rent, deposits, or escrow funds.</p></div><Link href="/safety">Safety guide <ExternalLink size={13} /></Link></section>
  </div></main>;
}
